create table if not exists public.logs_accesos (
  id bigint generated by default as identity primary key,
  usuario_id uuid references auth.users(id) on delete set null,
  email text,
  rol text,
  origen text not null default 'app',
  evento text not null check (evento in ('login', 'logout')),
  user_agent text,
  created_at timestamptz not null default now()
);

alter table public.logs_accesos enable row level security;

drop policy if exists logs_accesos_insercion_propia on public.logs_accesos;
create policy logs_accesos_insercion_propia
on public.logs_accesos for insert
to authenticated
with check ((select auth.uid()) = usuario_id);

drop policy if exists logs_accesos_lectura_encargado on public.logs_accesos;
create policy logs_accesos_lectura_encargado
on public.logs_accesos for select
to authenticated
using ((select private.es_encargado()));

grant select, insert on public.logs_accesos to authenticated;
grant usage, select on sequence public.logs_accesos_id_seq to authenticated;
