-- SOPORTE PARA MÚLTIPLES DIRECCIONES POR USUARIO

-- 1. CREAR TABLA DE DIRECCIONES
CREATE TABLE IF NOT EXISTS public.direcciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    perfil_id UUID REFERENCES public.perfiles(id) ON DELETE CASCADE NOT NULL,
    etiqueta TEXT NOT NULL, -- Ej: 'Casa', 'Trabajo'
    direccion_texto TEXT NOT NULL,
    latitud DOUBLE PRECISION NOT NULL,
    longitud DOUBLE PRECISION NOT NULL,
    es_principal BOOLEAN DEFAULT FALSE,
    creado_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
);

-- 2. HABILITAR SEGURIDAD RLS
ALTER TABLE public.direcciones ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Usuarios ven sus propias direcciones" ON public.direcciones;
CREATE POLICY "Usuarios ven sus propias direcciones"
ON public.direcciones FOR SELECT
TO authenticated
USING (auth.uid() = perfil_id);

DROP POLICY IF EXISTS "Usuarios insertan sus propias direcciones" ON public.direcciones;
CREATE POLICY "Usuarios insertan sus propias direcciones"
ON public.direcciones FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = perfil_id);

-- 3. ASEGURAR COLUMNAS EN PERFILES
ALTER TABLE public.perfiles ADD COLUMN IF NOT EXISTS acepto_politicas_registro BOOLEAN DEFAULT FALSE;

-- 4. ACTUALIZAR EL TRIGGER DE REGISTRO PARA PROCESAR EL ARRAY DE DIRECCIONES
-- Nota: Supabase Auth permite pasar JSON en raw_user_meta_data
CREATE OR REPLACE FUNCTION public.manejar_nuevo_usuario()
RETURNS TRIGGER AS $$
DECLARE
    direccion_item JSON;
BEGIN
  -- Insertar perfil básico
  INSERT INTO public.perfiles (id, email, nombre_completo, telefono, rol, acepto_politicas_registro)
  VALUES (
    new.id,
    new.email,
    COALESCE(new.raw_user_meta_data->>'nombre_completo', ''),
    COALESCE(new.raw_user_meta_data->>'telefono', ''),
    'cliente',
    TRUE
  );

  -- Insertar múltiples direcciones si vienen en el meta_data
  IF (new.raw_user_meta_data->'direcciones') IS NOT NULL THEN
    FOR direccion_item IN SELECT * FROM json_array_elements(new.raw_user_meta_data->'direcciones')
    LOOP
      INSERT INTO public.direcciones (perfil_id, etiqueta, direccion_texto, latitud, longitud)
      VALUES (
        new.id,
        direccion_item->>'etiqueta',
        direccion_item->>'direccion_texto',
        (direccion_item->>'latitud')::DOUBLE PRECISION,
        (direccion_item->>'longitud')::DOUBLE PRECISION
      );
    END LOOP;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
