-- TABLA PARA REGISTRO CENTRALIZADO DE ERRORES (LOGS)
CREATE TABLE IF NOT EXISTS public.logs_errores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clase_origen TEXT,
    metodo TEXT,
    mensaje_error TEXT,
    stack_trace TEXT,
    dispositivo TEXT,
    version_app TEXT,
    usuario_id UUID,
    creado_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
);

-- HABILITAR RLS
ALTER TABLE public.logs_errores ENABLE ROW LEVEL SECURITY;

-- PERMITIR QUE LA APP INSERTE LOGS (USANDO ANON O AUTHENTICATED)
CREATE POLICY "Permitir insertar logs a cualquiera"
ON public.logs_errores FOR INSERT
TO anon, authenticated
WITH CHECK (true);

-- SOLO EL ADMINISTRADOR PUEDE VER LOS LOGS
CREATE POLICY "Solo admin ve logs"
ON public.logs_errores FOR SELECT
TO authenticated
USING (EXISTS (SELECT 1 FROM public.perfiles WHERE id = auth.uid() AND rol = 'encargado'));
