-- TABLA PARA REGISTRAR LA ACEPTACIÓN DE POLÍTICAS EN CADA LOGIN
CREATE TABLE IF NOT EXISTS public.aceptaciones_login (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id UUID REFERENCES auth.users ON DELETE CASCADE,
    email TEXT,
    fecha_aceptacion TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    ip_address TEXT, -- Opcional, para mayor validez legal
    version_politica TEXT DEFAULT '1.0'
);

-- HABILITAR RLS
ALTER TABLE public.aceptaciones_login ENABLE ROW LEVEL SECURITY;

-- PERMITIR INSERTAR A USUARIOS AUTENTICADOS
CREATE POLICY "Usuarios pueden insertar su propia aceptacion"
ON public.aceptaciones_login FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = usuario_id);

-- ACTUALIZAR TABLA DE PERFILES PARA GUARDAR ACEPTACIÓN INICIAL
ALTER TABLE public.perfiles ADD COLUMN IF NOT EXISTS acepto_politicas_registro BOOLEAN DEFAULT FALSE;
ALTER TABLE public.perfiles ADD COLUMN IF NOT EXISTS fecha_aceptacion_registro TIMESTAMP WITH TIME ZONE;
