plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.uth.supereconomico'
    compileSdk {
        version = release(36) {
            minorApiLevel = 1
        }
    }

    defaultConfig {
        applicationId "com.uth.supereconomico"
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            optimization {
                enable false
            }
        }
    }
    viewBinding {
        enabled = true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    implementation libs.activity.ktx
    implementation libs.appcompat
    implementation libs.constraintlayout
    implementation libs.material
    implementation libs.core.splashscreen

    // Sincronización en segundo plano (Reemplazo de Firebase)
    implementation "androidx.work:work-runtime:2.9.1"
    implementation libs.ucrop

    // Networking
    implementation libs.retrofit
    implementation libs.retrofit.gson
    implementation libs.okhttp.logging

    // Lifecycle (MVVM)
    implementation libs.lifecycle.viewmodel
    implementation libs.lifecycle.livedata

    // Navigation
    implementation libs.navigation.fragment
    implementation libs.navigation.ui
    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"
    implementation "androidx.dynamicanimation:dynamicanimation:1.0.0"

    // Google Maps & Location
    implementation libs.google.maps
    implementation libs.google.location

    // Images
    implementation libs.glide
    annotationProcessor libs.glide.compiler

    testImplementation libs.junit
    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.ext.junit
}